trigger:
  branches:
    include:
      - main
  paths:
    include:
      - frontend/*

pool:
  vmImage: ubuntu-latest

variables:
  nodeVersion: '20.x'
  sshServiceConnection: 'prod-vm-ssh'

stages:

#=========================================
# BUILD
#=========================================

- stage: Build

  jobs:

  - job: Build

    steps:

    - checkout: self

    - task: NodeTool@0
      inputs:
        versionSpec: $(nodeVersion)

    - script: |
        cd frontend
        npm ci
        npm run build
      displayName: Build React App

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: frontend/build
        ArtifactName: react-build


#=========================================
# DEPLOY
#=========================================

- stage: Deploy

  dependsOn: Build

  jobs:

  - deployment: DeployFrontend

    environment: Production

    strategy:

      runOnce:

        deploy:

          steps:

          - task: DownloadBuildArtifacts@0
            inputs:
              artifactName: react-build
              downloadPath: $(Pipeline.Workspace)

          - task: CopyFilesOverSSH@0
            inputs:
              sshEndpoint: $(sshServiceConnection)
              sourceFolder: $(Pipeline.Workspace)/react-build
              targetFolder: /var/www/html

          - task: SSH@0
            displayName: Reload Nginx
            inputs:
              sshEndpoint: $(sshServiceConnection)
              runOptions: inline
              inline: |
                sudo nginx -t
                sudo systemctl reload nginx