trigger:
  branches:
    include:
      - main
  paths:
    include:
      - terraform/*

pool:
  vmImage: ubuntu-latest

variables:
  workingDirectory: terraform
  serviceConnection: terraform-service-con

#==========================
# VALIDATE
#==========================

stages:

- stage: Validate
  displayName: Terraform Validate

  jobs:
  - job: Validate

    steps:

    - checkout: self

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: latest

    - task: AzureCLI@2
      displayName: Terraform Init
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        workingDirectory: $(workingDirectory)
        inlineScript: |
          terraform init

    - script: |
        terraform fmt -check -recursive
      workingDirectory: $(workingDirectory)
      displayName: Terraform Format Check

    - script: |
        terraform validate
      workingDirectory: $(workingDirectory)
      displayName: Terraform Validate

#==========================
# PLAN
#==========================

- stage: Plan
  displayName: Terraform Plan
  dependsOn: Validate

  jobs:
  - job: Plan

    steps:

    - checkout: self

    - task: TerraformInstaller@1
      inputs:
        terraformVersion: latest

    - task: AzureCLI@2
      displayName: Terraform Plan
      inputs:
        azureSubscription: $(serviceConnection)
        scriptType: bash
        scriptLocation: inlineScript
        workingDirectory: $(workingDirectory)
        inlineScript: |
          terraform init
          terraform plan -out=tfplan

#==========================
# APPLY
#==========================

- stage: Apply
  displayName: Terraform Apply
  dependsOn: Plan

  jobs:

  - deployment: ApplyInfrastructure

    environment: dev

    strategy:

      runOnce:

        deploy:

          steps:

          - checkout: self

          - task: TerraformInstaller@1
            inputs:
              terraformVersion: latest

          - task: AzureCLI@2
            displayName: Terraform Apply
            inputs:
              azureSubscription: $(serviceConnection)
              scriptType: bash
              scriptLocation: inlineScript
              workingDirectory: $(workingDirectory)
              inlineScript: |
                terraform init
                terraform apply -auto-approve tfplan