trigger:
  branches:
    include:
      - main
  paths:
    include:
      - backend/*

pool:
  vmImage: ubuntu-latest

variables:
  nodeVersion: '20.x'
  sshServiceConnection: 'prod-vm-ssh'

stages:

#=========================================
# BUILD
#=========================================

- stage: Build
  displayName: Build Backend

  jobs:

  - job: Build

    steps:

    - checkout: self

    - task: NodeTool@0
      displayName: Install NodeJS
      inputs:
        versionSpec: $(nodeVersion)

    - script: |
        cd backend
        npm ci
      displayName: Install Dependencies

    - task: PublishBuildArtifacts@1
      displayName: Publish Backend Artifact
      inputs:
        PathtoPublish: backend
        ArtifactName: backend-artifact

#=========================================
# DEPLOY
#=========================================

- stage: Deploy
  displayName: Deploy Backend
  dependsOn: Build

  jobs:

  - deployment: DeployBackend
    displayName: Deploy Backend
    environment: Production

    strategy:
      runOnce:
        deploy:

          steps:

          - download: none

          - task: DownloadBuildArtifacts@0
            displayName: Download Backend Artifact
            inputs:
              buildType: current
              downloadType: single
              artifactName: backend-artifact
              downloadPath: $(Pipeline.Workspace)

          - task: CopyFilesOverSSH@0
            displayName: Copy Backend
            inputs:
              sshEndpoint: $(sshServiceConnection)
              sourceFolder: $(Pipeline.Workspace)/backend-artifact
              targetFolder: /home/azureuser/devops-interview-lab/backend
              cleanTargetFolder: false
              overwrite: true

          - task: SSH@0
            displayName: Deploy Backend
            inputs:
              sshEndpoint: $(sshServiceConnection)
              runOptions: inline
              inline: |
                set -e

                cd /home/azureuser/devops-interview-lab/backend

                npm install

                if pm2 describe backend >/dev/null 2>&1; then
                  echo "Restarting existing PM2 process..."
                  pm2 restart backend
                else
                  echo "Starting new PM2 process..."
                  pm2 start app.js --name backend
                fi

                pm2 save

                echo "Waiting for application..."
                sleep 10

                echo "Running Health Check..."

                RESPONSE=$(curl -fsS http://localhost:3000/api/health)

                echo "$RESPONSE"

                echo "$RESPONSE" | grep '"status":"UP"'

                echo "Backend deployed successfully."